### ISSUE TITLE
Overlap2D가져왔을때 문제

### ISSUE THREAD

**Issue by NakOh** [CienProject2014/OneLevelJson#28]
Default에 있는 것들은 (지도)는 이동이 되는데 

Arrow나 Text Layer에 있는 것들은 터치가 안먹힘. 수정이 안됨.

Convert to Button 해둔것들을 구분해서 보여주는 것이 있어야 수정할 수 있음. (이름수정이라던가)

**Comment by ChoiJIN** [comment]
Layer가 잠겨있으면 옮기거나 할 수 없다. Convert To Button은 아직 구현하지 않았음.
